### ISSUE TITLE
ブクマ対象のURLを正規化してほしい

### ISSUE THREAD

**Issue by suzukin** [directions4/easy_hatena#1]
PRする時間とスキルがないのでissueであげさせていただきました。
ソーシャルボタンからブクマしようとするとパラメータが付加され、アドオンやブックマークレットを使用しているユーザーとリンクが分散し、たとえば以下のような残念な結果になってしまいます。また、ページネーション時にも個別のURLが割り当てられています。
http://b.hatena.ne.jp/entry/thinkit.co.jp/story/2014/11/21/5368
http://b.hatena.ne.jp/entry/thinkit.co.jp/story/2014/11/21/5368?nopaging=1
## 現状

http://thinkit.co.jp/story/2014/12/05/5369
→　http://b.hatena.ne.jp/entry/thinkit.co.jp/story/2014/12/05/5369?nopaging=1

http://thinkit.co.jp/story/2014/12/05/5369/page/0/1
→　http://b.hatena.ne.jp/entry/thinkit.co.jp/story/2014/12/05/5369/page/0/1?page=0%2C1&nopaging=1
## 期待する結果

http://thinkit.co.jp/story/2014/12/05/5369
→　http://b.hatena.ne.jp/entry/thinkit.co.jp/story/2014/12/05/5369

http://thinkit.co.jp/story/2014/12/05/5369/page/0/1
→　http://b.hatena.ne.jp/entry/thinkit.co.jp/story/2014/12/05/5369

**Comment by directions4** [comment]
調べときます。

**Comment by directions4** [comment]
nopagingの方は、Smart Pagingの設定じゃないですか？
/admin/config/content/smart_paging
で、「Use the unpaged version as canonical」にチェックが入っていたら外してください。

http://thinkit.co.jp/story/2014/12/05/5369/page/0/1 は、そもそもブックマークされていないようですが・・・

基本的には、URIはcanonicalのものを出してますよ。

**Comment by suzukin** [comment]
さっそくありがとうございます、Smart Pagingのバージョンが古くて「Use the unpaged version as canonical」の項目がなかったので、そちらを見なおしてみます。

> 基本的には、URIはcanonicalのものを出してますよ。

了解しました。

**Comment by directions4** [comment]
Smart Paging、中身は見てないですが、このあたりでcanonical urlの修正しているみたいですよ。
https://www.drupal.org/node/1942266
https://www.drupal.org/commitlog/commit/15848/ed176027744c4aad62e12b9e3f23625088c6abad

**Comment by suzukin** [comment]
あ、まさしくこれっぽいですね！
ようやくステージング環境が整ったようなので検証してみます。

**Comment by suzukin** [comment]
Smart Pagingをバージョンアップすることで解決したのでクローズします。
